// Welcome to DAX query view! Learn more about DAX queries at https://aka.ms/dax-queries.
// Right-click on tables, columns, or measures in the data pane to access quick queries, or ask Copilot for help writing DAX.

// Select "Run" to try this sample DAX query.
Suicides by Year = 
VAR YearCount = DISTINCTCOUNT(Sheet1[the date])
VAR TotalSuicides = COUNTROWS(Sheet1)
RETURN
IF (
    YearCount = 1,
    TotalSuicides,            -- If only one year selected → show total suicides
    DIVIDE(TotalSuicides, YearCount)   -- If multiple years → average per year
)